name: Build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Initialize and start the MySQL database container
      - name: Start MySQL database
        run: docker run -d -p 3306:3306 --name mysql-db -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} mysql:latest

      # Wait for the MySQL database to start
      - name: Wait for MySQL database to start
        run: docker exec mysql-db mysqladmin --silent --wait=30 -uroot -p${{ secrets.DB_ROOT_PASSWORD }} ping

      # Build with Maven from the employee-management-api directory
      - name: Build with Maven
        run: mvn -f employee-system-api/pom.xml clean install
